name: Deploy New Version

on:
  repository_dispatch:
    types: [rollingversions_publish_approved]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 20
      uses: actions/setup-node@v6
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - name: npm install, build, test, publish
      run: |
        node --version
        npm --version
        npm ci
        npm run build --if-present
      env:
        CI: true
        NODE_OPTIONS: --openssl-legacy-provider
    - name: rollingversions check
      run: npx rollingversions publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # run: |
        # echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        # npx rollingversions publish -d -g ${{ secrets.GITHUB_TOKEN }}
        # npx rollingversions publish -g ${{ secrets.GITHUB_TOKEN }}
    - name: Copy dist to docs/examples/dist
      run: |
        npx cpx "dist/*" "docs/examples/dist"
    - name: Commit and push updated examples
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -f docs/examples/dist/*
        git commit -m "Update docs/examples/dist with latest build" || echo "No changes to commit"
        git push
